apiVersion: v1
kind: Service
metadata:
  name: details
  labels:
    app: details
    service: details
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.details.service.type }}
  ports:
    - port: {{ .Values.details.service.port}}
      name: http
      targetPort: 9080
      protocol: TCP
  selector:
    app: details
    release: {{ .Release.Name }}