apiVersion: v1
kind: Service
metadata:
  name: ratings
  labels:
    app: ratings
    release: {{ .Release.Name }}
    service: ratings
spec:
  type: {{ .Values.ratings.service.type }}
  ports:
    - port: {{ .Values.ratings.service.port }}
      targetPort: 9080
      name: http
  selector:
    app: ratings
    release: {{ .Release.Name }}
