apiVersion: v1
kind: Service
metadata:
  name: reviews
  labels:
    app: reviews
    release: {{ .Release.Name }}
    service: reviews
spec:
  type: {{ .Values.reviews.service.type }}
  ports:
    - port: {{ .Values.reviews.service.port }}
      targetPort: 9080
      name: http
  selector:
    app: reviews
    release: {{ .Release.Name }}
