apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: reviews
spec:
  host: reviews
  subsets:
    - name: v1
      labels:
        version: v1
    - name: v2
      labels:
        version: v2
    - name: v3
      labels:
        version: v3
---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: reviews
spec:
  hosts:
    - reviews
  http:
    - route:
        - destination:
            host: reviews
            subset: v1
          weight: {{ .Values.reviews.weight.v1 }}
        - destination:
            host: reviews
            subset: v2
          weight: {{ .Values.reviews.weight.v2 }}
        - destination:
            host: reviews
            subset: v3
          weight: {{ .Values.reviews.weight.v3 }}
