# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@master
      
      # push images to dockerhub
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_NAME }}
          password: ${{ secrets.DOCKER_HUB_PASS }}

      - name: PUSH IMAGES
        run: make USER_ID=${{ secrets.DOCKER_HUB_NAME }} commit

      # run services in kind with helm chart
      - name: Create cluster
        run: make Install_kind
        
      - name: install istio
        run: make Install_istio

      - name : run services  
        run: helm install --set reviews.weight.v1=15 --set reviews.weight.v2=15 --set reviews.weight.v3=70 bookstio ./chart
        
      - name : prepare to test
        run : chmod +x ./test.sh
        
      - name : wait to build
        run: ./test.sh
        
      - name : get pod
        run : kubectl get pod

      - name: show result
        run: ./test.sh
